export const COMMENTS = [
  {
    id: 0,
    hotelsiteId: 0,
    rating: 5,
    text: "Hyatt Place -What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 1,
    hotelsiteId: 0,
    rating: 4,
    text:
      "Hyatt Place - The campground was beautiful, but the bugs could bite sometimes.",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 2,
    hotelsiteId: 0,
    rating: 5,
    text:
      "Hyatt Place - I caught a world-record-breaking trout here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 3,
    hotelsiteId: 0,
    rating: 5,
    text: "Hyatt Place - A wonderful place to reconnect with nature.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 4,
    hotelsiteId: 0,
    rating: 4,
    text: "Hyatt Place - The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 5,
    hotelsiteId: 1,
    rating: 4,
    text:
      "Hyatt Place - The campground was beautiful, but the bugs could bite sometimes.",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 6,
    hotelsiteId: 1,
    rating: 5,
    text:
      "Duxton Inn - I caught a world-record-breaking trout here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 7,
    hotelsiteId: 1,
    rating: 5,
    text: "Duxton Inn - A wonderful place to reconnect with nature.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 8,
    hotelsiteId: 1,
    rating: 4,
    text: "Duxton Inn - The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 9,
    hotelsiteId: 1,
    rating: 5,
    text: "Duxton Inn - What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 10,
    hotelsiteId: 2,
    rating: 5,
    text:
      "Holiday Inn - I caught a world-record-breaking trout here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 11,
    hotelsiteId: 2,
    rating: 5,
    text: "Holiday Inn - A wonderful place to reconnect with nature.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 12,
    hotelsiteId: 2,
    rating: 4,
    text: "Holiday Inn - The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 13,
    hotelsiteId: 2,
    rating: 5,
    text: "Holiday Inn - What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 14,
    hotelsiteId: 2,
    rating: 4,
    text:
      "Holiday Inn - The campground was beautiful, but the bugs could bite sometimes.",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 15,
    hotelsiteId: 3,
    rating: 5,
    text: "A wonderful place to reconnect with nature.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 16,
    hotelsiteId: 3,
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 17,
    hotelsiteId: 3,
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 18,
    hotelsiteId: 3,
    rating: 4,
    text: "The campground was beautiful, but the bugs could bite sometimes.",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 19,
    hotelsiteId: 3,
    rating: 5,
    text: "I caught a world-record-breaking trout here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
];
