export const ADD_COMMENT = "ADD_COMMENT";
export const HOTELSITES_LOADING = "HOTELSITES_LOADING";
export const HOTELSITES_FAILED = "HOTELSITES_FAILED";
export const ADD_HOTELSITES = "ADD_HOTELSITES";
