export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const ADD_HOTELSITES = "ADD_HOTELSITES";
export const HOTELSITES_LOADING = "HOTELSITES_LOADING";
export const HOTELSITES_FAILED = "HOTELSITES_FAILED";

export const ADD_PROMOTIONS = "ADD_PROMOTIONS";
export const PROMOTIONS_LOADING = "PROMOTIONS_LOADING";
export const PROMOTIONS_FAILED = "PROMOTIONS_FAILED";

export const ADD_PARTNERS = "ADD_PARTNERS";
export const PARTNERS_LOADING = "PARTNERS_LOADING";
export const PARTNERS_FAILED = "PARTNERS_FAILED";

export const SEARCH = "SEARCH";
